### ISSUE TITLE
JetstrapFacade::useAdminLte3();

### ISSUE THREAD

**Issue by khakimjanovich** [nascent-africa/jetstrap#75]
when executing npm run dev

ERROR in ./resources/sass/dashboard/dashboard.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
  ╷
7 │   &.bg-#{$name} {
  │   ^^^^^^^^^^^^^^
  ╵
  node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()
  node_modules/admin-lte/build/scss/_colors.scss 7:3               @import
  node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import
  resources/sass/dashboard/dashboard.scss 31:9                     root stylesheet
    at processResult (./node_modules/webpack/lib/NormalModule.js:758:19)
    at ./node_modules/webpack/lib/NormalModule.js:860:5
    at ./starterL9/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at ./node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (./node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (./node_modules/sass-loader/dist/index.js:69:5)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors

**Comment by emjay64** [comment]
@khakimjanovich I am getting the same error, did you manage to fix this?

**Comment by wmomesso** [comment]
@khakimjanovich my errors

root@71775e140091:/var/www/lara-app# npm update
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: bootstrap-switch@3.3.4
npm WARN Found: bootstrap@4.6.1
npm WARN node_modules/bootstrap
npm WARN   dev bootstrap@"^4.6.0" from the root project
npm WARN   3 more (admin-lte, bootstrap-colorpicker, tempusdominus-bootstrap-4)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer bootstrap@"^3.1.1" from bootstrap-switch@3.3.4
npm WARN node_modules/bootstrap-switch
npm WARN   bootstrap-switch@"3.3.4" from admin-lte@3.2.0
npm WARN   node_modules/admin-lte
npm WARN 
npm WARN Conflicting peer dependency: bootstrap@3.4.1
npm WARN node_modules/bootstrap
npm WARN   peer bootstrap@"^3.1.1" from bootstrap-switch@3.3.4
npm WARN   node_modules/bootstrap-switch
npm WARN     bootstrap-switch@"3.3.4" from admin-lte@3.2.0
npm WARN     node_modules/admin-lte

up to date, audited 950 packages in 5s

85 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

did you manage to fix this?
